//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerID { get; set; }
        public string customerName { get; set; }
        public byte wait { get; set; }
        public byte reservation { get; set; }
        public System.DateTime timeIn { get; set; }
        public System.DateTime timeMade { get; set; }
    }
}
