//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatingManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeatingManagerDBEntities : DbContext
    {
        public SeatingManagerDBEntities()
            : base("name=SeatingManagerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assigncustomer> assigncustomers { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<tablemap> tablemaps { get; set; }
        public virtual DbSet<tablemerge> tablemerges { get; set; }
        public virtual DbSet<tablesection> tablesections { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
