//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablemerge
    {
        public int tableMergeID { get; set; }
        public int tableID1 { get; set; }
        public int tableID2 { get; set; }
        public Nullable<int> tableID3 { get; set; }
        public Nullable<int> tableID4 { get; set; }
        public byte visible { get; set; }
        public byte isMerged { get; set; }
    }
}
