//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablemap
    {
        public int tableID { get; set; }
        public Nullable<int> tableX { get; set; }
        public Nullable<int> tableY { get; set; }
        public int numberOfSeats { get; set; }
        public byte visible { get; set; }
        public int sectionID { get; set; }
        public int tableType { get; set; }
    }
}
