//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phone { get; set; }
        public int role { get; set; }
        public byte isActive { get; set; }
        public byte isOnDuty { get; set; }
        public int sectionID { get; set; }
        public string password { get; set; }
        public string title { get; set; }
        public System.DateTime dateHired { get; set; }
    }
}
